stages:
  data_ingestion:
    cmd: python src\cnnClassifier\pipeline\stag01_data_ingestion.py
    deps:
        - src\cnnClassifier\pipeline\stag01_data_ingestion.py
        - config\config.yaml
    outs:
        - artifacts\data_ingestion\kidney-ct-scan-image


  prepare_base_model:
    cmd: python src\cnnClassifier\pipeline\stage02_prepare_base_model.py
    deps:
        - src\cnnClassifier\pipeline\stage02_prepare_base_model.py
        - config\config.yaml
    params:
        - IMAGE_SIZE
        - INCLUDE_TOP
        - WEIGHTS
        - CLASSES
        - LEARNING_RATE
    outs:
        - artifacts\prepare_base_model

  train_model:
    cmd: python src\cnnClassifier\pipeline\stage03_model_training.py
    deps:
        - src\cnnClassifier\pipeline\stage03_model_training.py
        - artifacts\prepare_base_model
        - config\config.yaml
        - artifacts\data_ingestion\kidney-ct-scan-image
    params:
        - BATCH_SIZE
        - EPOCHS
        - AUGMENTATION
        - IMAGE_SIZE
    outs:
        - artifacts\training\model.h5

  evaluate_model:
    cmd: python src\cnnClassifier\pipeline\stage04_model_evaluation.py
    deps:
        - src\cnnClassifier\pipeline\stage04_model_evaluation.py
        - artifacts\training\model.h5
        - config\config.yaml
        - artifacts\data_ingestion\kidney-ct-scan-image
    params:
        - BATCH_SIZE
        - IMAGE_SIZE
    metrics:
        - scores.json:
            cache: false